# Generated by Django 5.1 on 2024-10-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenProducto/'),
        ),
    ]
