# Generated by Django 5.1 on 2024-09-12 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelefono', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Número de teléfono')),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Chaco', 'Chaco'), ('Corrientes', 'Corrientes'), ('Formosa', 'Formosa')], max_length=15, verbose_name='Provincia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'ClienteT',
            },
        ),
    ]
